# Generated by Django 5.2.7 on 2025-10-15 16:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Auto'), ('TRUCK', 'Camioneta'), ('MOTORCYCLE', 'Moto')], max_length=20, unique=True, verbose_name='Tipo de Vehículo')),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Costo por hora de estacionamiento', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarifa por Hora')),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Costo por día de estacionamiento', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarifa Diaria')),
                ('monthly_rate', models.DecimalField(decimal_places=2, help_text='Costo por mes de estacionamiento', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarifa Mensual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Tarifa Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Tarifa de Vehículo',
                'verbose_name_plural': 'Tarifas de Vehículos',
                'ordering': ['vehicle_type'],
            },
        ),
        migrations.CreateModel(
            name='ParkingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_floors', models.PositiveIntegerField(help_text='Número total de pisos en el estacionamiento', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total de Pisos')),
                ('spaces_per_floor', models.PositiveIntegerField(help_text='Cantidad de espacios de estacionamiento por piso', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Espacios por Piso')),
                ('is_active', models.BooleanField(default=True, help_text='Solo puede haber una configuración activa', verbose_name='Configuración Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_configurations', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Configuración de Estacionamiento',
                'verbose_name_plural': 'Configuraciones de Estacionamiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParkingFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Piso')),
                ('floor_name', models.CharField(blank=True, help_text='Ej: Piso 1, Sótano 1, etc.', max_length=50, verbose_name='Nombre del Piso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Piso Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='parking.parkingconfiguration', verbose_name='Configuración')),
            ],
            options={
                'verbose_name': 'Piso de Estacionamiento',
                'verbose_name_plural': 'Pisos de Estacionamiento',
                'ordering': ['floor_number'],
                'unique_together': {('configuration', 'floor_number')},
            },
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Espacio')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('OCCUPIED', 'Ocupado'), ('RESERVED', 'Reservado'), ('MAINTENANCE', 'En Mantenimiento')], default='AVAILABLE', max_length=20, verbose_name='Estado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Espacio Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='parking.parkingfloor', verbose_name='Piso')),
            ],
            options={
                'verbose_name': 'Espacio de Estacionamiento',
                'verbose_name_plural': 'Espacios de Estacionamiento',
                'ordering': ['floor__floor_number', 'space_number'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Auto'), ('TRUCK', 'Camioneta'), ('MOTORCYCLE', 'Moto')], max_length=20, verbose_name='Tipo de Vehículo')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Año')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
                ('license_plate', models.CharField(help_text='Número de placa del vehículo', max_length=20, unique=True, verbose_name='Placa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParkingReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado'), ('COMPLETED', 'Completado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('reservation_date', models.DateTimeField(help_text='Fecha y hora para la cual se reserva', verbose_name='Fecha de Reserva')),
                ('duration_hours', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración (horas)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('parking_space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='parking.parkingspace', verbose_name='Espacio Asignado')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='parking.vehicle', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Reserva de Estacionamiento',
                'verbose_name_plural': 'Reservas de Estacionamiento',
                'ordering': ['-reservation_date'],
            },
        ),
        migrations.CreateModel(
            name='ParkingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('entry_time', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Entrada')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('planned_exit_time', models.DateTimeField(blank=True, help_text='Hora estimada de salida', null=True, verbose_name='Hora de Salida Planificada')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Total')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_assignments_created', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_assignments_completed', to=settings.AUTH_USER_MODEL, verbose_name='Completado por')),
                ('parking_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='parking.parkingspace', verbose_name='Espacio de Estacionamiento')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_assignments', to='parking.vehicle', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Asignación de Estacionamiento',
                'verbose_name_plural': 'Asignaciones de Estacionamiento',
                'ordering': ['-entry_time'],
            },
        ),
        migrations.AddIndex(
            model_name='parkingspace',
            index=models.Index(fields=['status', 'is_active'], name='parking_par_status_defe66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parkingspace',
            unique_together={('floor', 'space_number')},
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['license_plate'], name='parking_veh_license_96464d_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['owner', 'is_active'], name='parking_veh_owner_i_cc3971_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingreservation',
            index=models.Index(fields=['status', 'reservation_date'], name='parking_par_status_a410f6_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingreservation',
            index=models.Index(fields=['user', 'status'], name='parking_par_user_id_0e410c_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingassignment',
            index=models.Index(fields=['status', 'entry_time'], name='parking_par_status_c504d4_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingassignment',
            index=models.Index(fields=['vehicle', 'status'], name='parking_par_vehicle_fca147_idx'),
        ),
    ]
