# Generated by Django 5.2.7 on 2025-10-15 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingreservation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Trabajador o admin que creó la reserva', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='parkingreservation',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Para reservas rápidas sin usuario registrado', max_length=254, verbose_name='Email del Cliente'),
        ),
        migrations.AddField(
            model_name='parkingreservation',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Para reservas rápidas sin usuario registrado', max_length=100, verbose_name='Nombre del Cliente'),
        ),
        migrations.AddField(
            model_name='parkingreservation',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Para reservas rápidas sin usuario registrado', max_length=20, verbose_name='Teléfono del Cliente'),
        ),
        migrations.AddField(
            model_name='parkingreservation',
            name='is_quick_reservation',
            field=models.BooleanField(default=False, help_text='Indica si es una reserva rápida/manual sin usuario registrado', verbose_name='Reserva Rápida'),
        ),
        migrations.AddField(
            model_name='parkingreservation',
            name='vehicle_plate',
            field=models.CharField(blank=True, help_text='Para reservas rápidas sin vehículo registrado', max_length=20, verbose_name='Placa del Vehículo'),
        ),
        migrations.AddField(
            model_name='parkingreservation',
            name='vehicle_type_temp',
            field=models.CharField(blank=True, choices=[('CAR', 'Auto'), ('TRUCK', 'Camioneta'), ('MOTORCYCLE', 'Moto')], help_text='Para reservas rápidas sin vehículo registrado', max_length=20, verbose_name='Tipo de Vehículo (Temporal)'),
        ),
        migrations.AlterField(
            model_name='parkingreservation',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuario registrado. Dejar en blanco para reserva rápida/manual', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='parkingreservation',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Vehículo registrado. Dejar en blanco para reserva rápida/manual', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='parking.vehicle', verbose_name='Vehículo'),
        ),
        migrations.AddIndex(
            model_name='parkingreservation',
            index=models.Index(fields=['is_quick_reservation', 'status'], name='parking_par_is_quic_7c22dd_idx'),
        ),
    ]
