# Generated by Django 5.0 on 2025-11-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_vehicle_brand_alter_vehicle_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingassignment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('YAPE', 'Yape'), ('PLIN', 'Plin')], max_length=20, null=True, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='parkingassignment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de Boleta'),
        ),
    ]
