# Generated by Django 5.0 on 2025-11-19 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_parkingassignment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletariff',
            name='rate_per_hour',
            field=models.DecimalField(decimal_places=2, help_text='Costo por hora de estacionamiento en Soles', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarifa por Hora (S/)'),
        ),
    ]
