# Generated by Django 5.0 on 2025-12-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_alter_vehicletariff_rate_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletariff',
            name='description',
            field=models.CharField(blank=True, help_text='Nombre personalizado para mostrar en la tarifa (opcional)', max_length=100, verbose_name='Descripción'),
        ),
    ]
