# Generated by Django 5.0 on 2025-12-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_vehicletariff_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletariff',
            name='custom_name',
            field=models.CharField(blank=True, help_text='Nombre para mostrar en lugar del tipo por defecto (ej: "Sedan" en vez de "Auto")', max_length=50, verbose_name='Nombre Personalizado'),
        ),
    ]
